### ISSUE TITLE
Exception when using git flow

### ISSUE THREAD

**Issue by jhoelzl** [wspringer/difr#2]
Hello,

i have installed git, git flow and difr,

This works:

```
git diff| java -jar difr.jar > diff_test.html
```

But why does a git diff of branches does not work?

```
git diff testing master| java -jar difr.jar > diff_test.html
```

With this command i get the following error:

Exception in thread "main" java.lang.RuntimeException: `--- ' expected but`B' found at 54.1
        at scala.sys.package$.error(package.scala:27)
        at nl.flotsam.difr.GitDiffParser$.asDiffs(GitDiff.scala:114)
        at nl.flotsam.difr.Tool$.nl$flotsam$difr$Tool$$parse(Tool.scala:107)
        at nl.flotsam.difr.Tool$$anonfun$main$1.apply(Tool.scala:91)
        at nl.flotsam.difr.Tool$$anonfun$main$1.apply(Tool.scala:91)
        at nl.flotsam.difr.Tool$.usingIn(Tool.scala:67)
        at nl.flotsam.difr.Tool$.main(Tool.scala:91)
        at nl.flotsam.difr.Tool.main(Tool.scala)

Thanks!

**Comment by wspringer** [comment]
Probably because the parser is limited. :-(

It seems parsing git logs is quite hard. I stole the parser from another project and then beat it into shape for my purpose, but it might actually be a good idea to write a new one from scratch.

You might want to try to add the —color=never switch to your git command. That might help.

-- 
Wilfred Springer
+31 612 981 670
http://nxt.flotsam.nl/      

On 19 Feb 2015 at 14:38:50, Jomage (notifications@github.com) wrote:

Hello,

i have installed git, git flow and difr,

This works:

git diff| java -jar difr.jar > diff_test.html

But why does a git diff of branches does not work?

git diff testing master| java -jar difr.jar > diff_test.html

With this command i get the following error:

Exception in thread "main" java.lang.RuntimeException: --- ' expected butB' found at 54.1
at scala.sys.package$.error(package.scala:27)
at nl.flotsam.difr.GitDiffParser$.asDiffs(GitDiff.scala:114)
at nl.flotsam.difr.Tool$.nl$flotsam$difr$Tool$$parse(Tool.scala:107)
at nl.flotsam.difr.Tool$$anonfun$main$1.apply(Tool.scala:91)
at nl.flotsam.difr.Tool$$anonfun$main$1.apply(Tool.scala:91)
at nl.flotsam.difr.Tool$.usingIn(Tool.scala:67)
at nl.flotsam.difr.Tool$.main(Tool.scala:91)
at nl.flotsam.difr.Tool.main(Tool.scala)

Thanks!

**Comment by jhoelzl** [comment]
Hello,

thanks for your reply! I tried --color=never, but without success.
